# -*- coding: utf-8 -*-
"""vehicle_fuel_deployment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U1dCO9_5h3KWHW_fkgpSTZvv-G8qmaTr
"""

import streamlit as st
import pandas as pd
import joblib


model = joblib.load("vehicle_fuel_deployment.pkl")
encoder = joblib.load("label_encoder.pkl")


st.title("vehicle_fuel_deployment app")


cylinders = st.number_input("cylinders")
displacement = st.number_input("displacement")
horsepower = st.number_input("horsepower")
weight = st.number_input("weight", 0,40)
acceleration = st.number_input("acceleration", 0,40)
modelyear = st.number_input("model_year", 0,40)
origin = st.number_input("origin", 0,40)
carname = st.selectbox("car name",encoder["car_name"].classes_)


df = pd.dataFrame({
    "cylinders":[cylinders],
    "displacement":[displacement],
    "horsepower":[horsepower],
    "weight":[weight],
    "acceleration":[acceleration],
    "model_year":[modelyear],
    "origin":[origin]
})


if st.button("Predict"):
  for col in encoder:
    df[col] = encoder[col].transform(df[col])

  prediction = model.predict(df)
  st.success(f"Predicted vehicle: {prediction[0]:,.2f}")
